/*
 * generated by Xtext 2.32.0
 */
package org.bigraphs.dsl.parser.antlr;

import com.google.inject.Inject;
import org.bigraphs.dsl.parser.antlr.internal.InternalBDSLParser;
import org.bigraphs.dsl.services.BDSLGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class BDSLParser extends AbstractAntlrParser {

	@Inject
	private BDSLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalBDSLParser createParser(XtextTokenStream stream) {
		return new InternalBDSLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "BDSLDocument";
	}

	public BDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(BDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
