/**
 * generated by Xtext 2.15.0
 */
package de.tudresden.inf.st.bigraphs.dsl.tests;

import com.google.inject.Inject;
import de.tudresden.inf.st.bigraphs.dsl.bDSL.BRSModel;
import de.tudresden.inf.st.bigraphs.dsl.tests.BDSLInjectorProvider;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

@ExtendWith(InjectionExtension.class)
@InjectWith(BDSLInjectorProvider.class)
@SuppressWarnings("all")
public class BDSLParsingTest {
  @Inject
  private ParseHelper<BRSModel> parseHelper;
  
  @Test
  public void loadModel() {
  }
}
