/**
 * generated by Xtext 2.21.0
 */
package de.tudresden.inf.st.bigraphs.dsl.scoping;

import de.tudresden.inf.st.bigraphs.dsl.scoping.AbstractBDSLScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class BDSLScopeProvider extends AbstractBDSLScopeProvider {
}
