/**
 * generated by Xtext 2.21.0
 */
package de.tudresden.inf.st.bigraphs.dsl;

import de.tudresden.inf.st.bigraphs.dsl.BDSLStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class BDSLStandaloneSetup extends BDSLStandaloneSetupGenerated {
  public static void doSetup() {
    new BDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
