/**
 * generated by Xtext 2.21.0
 */
package de.tudresden.inf.st.bigraphs.dsl.bDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Bigraph Var Reference</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.tudresden.inf.st.bigraphs.dsl.bDSL.BigraphVarReference#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see de.tudresden.inf.st.bigraphs.dsl.bDSL.BDSLPackage#getBigraphVarReference()
 * @model
 * @generated
 */
public interface BigraphVarReference extends AbstractBigraphDeclaration, AbstractMainStatements, PrintableExpression
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' reference.
   * @see #setValue(LocalVarDecl)
   * @see de.tudresden.inf.st.bigraphs.dsl.bDSL.BDSLPackage#getBigraphVarReference_Value()
   * @model
   * @generated
   */
  LocalVarDecl getValue();

  /**
   * Sets the value of the '{@link de.tudresden.inf.st.bigraphs.dsl.bDSL.BigraphVarReference#getValue <em>Value</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' reference.
   * @see #getValue()
   * @generated
   */
  void setValue(LocalVarDecl value);

} // BigraphVarReference
