/**
 * generated by Xtext 2.21.0
 */
package de.tudresden.inf.st.bigraphs.dsl.bDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Main Element</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.tudresden.inf.st.bigraphs.dsl.bDSL.BDSLPackage#getMainElement()
 * @model
 * @generated
 */
public interface MainElement extends EObject
{
} // MainElement
