/**
 * generated by Xtext 2.21.0
 */
package de.tudresden.inf.st.bigraphs.dsl.bDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Main Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.tudresden.inf.st.bigraphs.dsl.bDSL.MainDeclaration#getDefinition <em>Definition</em>}</li>
 * </ul>
 *
 * @see de.tudresden.inf.st.bigraphs.dsl.bDSL.BDSLPackage#getMainDeclaration()
 * @model
 * @generated
 */
public interface MainDeclaration extends EObject
{
  /**
   * Returns the value of the '<em><b>Definition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Definition</em>' containment reference.
   * @see #setDefinition(AbstractMainStatements)
   * @see de.tudresden.inf.st.bigraphs.dsl.bDSL.BDSLPackage#getMainDeclaration_Definition()
   * @model containment="true"
   * @generated
   */
  AbstractMainStatements getDefinition();

  /**
   * Sets the value of the '{@link de.tudresden.inf.st.bigraphs.dsl.bDSL.MainDeclaration#getDefinition <em>Definition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Definition</em>' containment reference.
   * @see #getDefinition()
   * @generated
   */
  void setDefinition(AbstractMainStatements value);

} // MainDeclaration
