/**
 * generated by Xtext 2.21.0
 */
package de.tudresden.inf.st.bigraphs.dsl.bDSL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Node Expression Call</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.tudresden.inf.st.bigraphs.dsl.bDSL.NodeExpressionCall#getValue <em>Value</em>}</li>
 *   <li>{@link de.tudresden.inf.st.bigraphs.dsl.bDSL.NodeExpressionCall#getLinks <em>Links</em>}</li>
 * </ul>
 *
 * @see de.tudresden.inf.st.bigraphs.dsl.bDSL.BDSLPackage#getNodeExpressionCall()
 * @model
 * @generated
 */
public interface NodeExpressionCall extends AbstractBigraphDeclaration
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' reference.
   * @see #setValue(ControlVariable)
   * @see de.tudresden.inf.st.bigraphs.dsl.bDSL.BDSLPackage#getNodeExpressionCall_Value()
   * @model
   * @generated
   */
  ControlVariable getValue();

  /**
   * Sets the value of the '{@link de.tudresden.inf.st.bigraphs.dsl.bDSL.NodeExpressionCall#getValue <em>Value</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' reference.
   * @see #getValue()
   * @generated
   */
  void setValue(ControlVariable value);

  /**
   * Returns the value of the '<em><b>Links</b></em>' containment reference list.
   * The list contents are of type {@link de.tudresden.inf.st.bigraphs.dsl.bDSL.LinkNames}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Links</em>' containment reference list.
   * @see de.tudresden.inf.st.bigraphs.dsl.bDSL.BDSLPackage#getNodeExpressionCall_Links()
   * @model containment="true"
   * @generated
   */
  EList<LinkNames> getLinks();

} // NodeExpressionCall
