/**
 * generated by Xtext 2.21.0
 */
package de.tudresden.inf.st.bigraphs.dsl.bDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Printable Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.tudresden.inf.st.bigraphs.dsl.bDSL.BDSLPackage#getPrintableExpression()
 * @model
 * @generated
 */
public interface PrintableExpression extends EObject
{
} // PrintableExpression
