/**
 * generated by Xtext 2.32.0
 */
package org.bigraphs.dsl.bDSL.impl;

import org.bigraphs.dsl.bDSL.BDSLPackage;
import org.bigraphs.dsl.bDSL.BigraphPredDeclOrReference;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Bigraph Pred Decl Or Reference</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class BigraphPredDeclOrReferenceImpl extends MinimalEObjectImpl.Container implements BigraphPredDeclOrReference
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BigraphPredDeclOrReferenceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BDSLPackage.Literals.BIGRAPH_PRED_DECL_OR_REFERENCE;
  }

} //BigraphPredDeclOrReferenceImpl
