/**
 * generated by Xtext 2.32.0
 */
package org.bigraphs.dsl.bDSL.impl;

import org.bigraphs.dsl.bDSL.BDSLPackage;
import org.bigraphs.dsl.bDSL.BRSFinishedCallback;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>BRS Finished Callback</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class BRSFinishedCallbackImpl extends BdslCallbackMethodsImpl implements BRSFinishedCallback
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BRSFinishedCallbackImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BDSLPackage.Literals.BRS_FINISHED_CALLBACK;
  }

} //BRSFinishedCallbackImpl
