/**
 * generated by Xtext 2.32.0
 */
package org.bigraphs.dsl.bDSL.impl;

import org.bigraphs.dsl.bDSL.BDSLPackage;
import org.bigraphs.dsl.bDSL.ElementaryBigraphs;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Elementary Bigraphs</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ElementaryBigraphsImpl extends AbstractBigraphDeclarationImpl implements ElementaryBigraphs
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ElementaryBigraphsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BDSLPackage.Literals.ELEMENTARY_BIGRAPHS;
  }

} //ElementaryBigraphsImpl
