/**
 * generated by Xtext 2.15.0
 */
package de.tudresden.inf.st.bigraphs.dsl.ui;

import com.google.inject.Binder;
import de.tudresden.inf.st.bigraphs.dsl.ui.labeling.BDSLLabelProvider;
import org.eclipse.jface.viewers.ILabelProvider;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.eclipse.xtext.ui.editor.contentassist.ContentProposalLabelProvider;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class BDSLUiModule /* implements AbstractBDSLUiModule  */{
  @Override
  public void configureContentProposalLabelProvider(final Binder binder) {
    binder.<ILabelProvider>bind(ILabelProvider.class).annotatedWith(ContentProposalLabelProvider.class).to(BDSLLabelProvider.class);
  }
}
