/**
 * generated by Xtext 2.32.0
 */
package org.bigraphs.dsl.bDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Abstract Bigraph Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.bigraphs.dsl.bDSL.BDSLPackage#getAbstractBigraphDeclaration()
 * @model
 * @generated
 */
public interface AbstractBigraphDeclaration extends BigraphExpression
{
} // AbstractBigraphDeclaration
