/**
 * generated by Xtext 2.32.0
 */
package org.bigraphs.dsl.bDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Abstract Named Signature Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.bigraphs.dsl.bDSL.AbstractNamedSignatureElement#getSig <em>Sig</em>}</li>
 * </ul>
 *
 * @see org.bigraphs.dsl.bDSL.BDSLPackage#getAbstractNamedSignatureElement()
 * @model
 * @generated
 */
public interface AbstractNamedSignatureElement extends UDFArgumentTypes
{
  /**
   * Returns the value of the '<em><b>Sig</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sig</em>' reference.
   * @see #setSig(Signature)
   * @see org.bigraphs.dsl.bDSL.BDSLPackage#getAbstractNamedSignatureElement_Sig()
   * @model
   * @generated
   */
  Signature getSig();

  /**
   * Sets the value of the '{@link org.bigraphs.dsl.bDSL.AbstractNamedSignatureElement#getSig <em>Sig</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sig</em>' reference.
   * @see #getSig()
   * @generated
   */
  void setSig(Signature value);

} // AbstractNamedSignatureElement
