/**
 * generated by Xtext 2.32.0
 */
package org.bigraphs.dsl.bDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Reference Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.bigraphs.dsl.bDSL.BDSLReferenceDeclaration#getTarget <em>Target</em>}</li>
 * </ul>
 *
 * @see org.bigraphs.dsl.bDSL.BDSLPackage#getBDSLReferenceDeclaration()
 * @model
 * @generated
 */
public interface BDSLReferenceDeclaration extends AssignmentOrVariableDeclaration
{
  /**
   * Returns the value of the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' reference.
   * @see #setTarget(AbstractNamedSignatureElement)
   * @see org.bigraphs.dsl.bDSL.BDSLPackage#getBDSLReferenceDeclaration_Target()
   * @model
   * @generated
   */
  AbstractNamedSignatureElement getTarget();

  /**
   * Sets the value of the '{@link org.bigraphs.dsl.bDSL.BDSLReferenceDeclaration#getTarget <em>Target</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' reference.
   * @see #getTarget()
   * @generated
   */
  void setTarget(AbstractNamedSignatureElement value);

} // BDSLReferenceDeclaration
