/**
 * generated by Xtext 2.32.0
 */
package org.bigraphs.dsl.bDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Brs Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.bigraphs.dsl.bDSL.BDSLBrsDefinition#getBrs <em>Brs</em>}</li>
 *   <li>{@link org.bigraphs.dsl.bDSL.BDSLBrsDefinition#getAgents <em>Agents</em>}</li>
 *   <li>{@link org.bigraphs.dsl.bDSL.BDSLBrsDefinition#getRules <em>Rules</em>}</li>
 *   <li>{@link org.bigraphs.dsl.bDSL.BDSLBrsDefinition#getPredicates <em>Predicates</em>}</li>
 * </ul>
 *
 * @see org.bigraphs.dsl.bDSL.BDSLPackage#getBDSLBrsDefinition()
 * @model
 * @generated
 */
public interface BDSLBrsDefinition extends EObject
{
  /**
   * Returns the value of the '<em><b>Brs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Brs</em>' containment reference.
   * @see #setBrs(AssignableBigraphExpressionWithExplicitSig)
   * @see org.bigraphs.dsl.bDSL.BDSLPackage#getBDSLBrsDefinition_Brs()
   * @model containment="true"
   * @generated
   */
  AssignableBigraphExpressionWithExplicitSig getBrs();

  /**
   * Sets the value of the '{@link org.bigraphs.dsl.bDSL.BDSLBrsDefinition#getBrs <em>Brs</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Brs</em>' containment reference.
   * @see #getBrs()
   * @generated
   */
  void setBrs(AssignableBigraphExpressionWithExplicitSig value);

  /**
   * Returns the value of the '<em><b>Agents</b></em>' containment reference list.
   * The list contents are of type {@link org.bigraphs.dsl.bDSL.BigraphVarReference}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Agents</em>' containment reference list.
   * @see org.bigraphs.dsl.bDSL.BDSLPackage#getBDSLBrsDefinition_Agents()
   * @model containment="true"
   * @generated
   */
  EList<BigraphVarReference> getAgents();

  /**
   * Returns the value of the '<em><b>Rules</b></em>' containment reference list.
   * The list contents are of type {@link org.bigraphs.dsl.bDSL.RuleVarReference}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rules</em>' containment reference list.
   * @see org.bigraphs.dsl.bDSL.BDSLPackage#getBDSLBrsDefinition_Rules()
   * @model containment="true"
   * @generated
   */
  EList<RuleVarReference> getRules();

  /**
   * Returns the value of the '<em><b>Predicates</b></em>' containment reference list.
   * The list contents are of type {@link org.bigraphs.dsl.bDSL.PredicateVarReference}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Predicates</em>' containment reference list.
   * @see org.bigraphs.dsl.bDSL.BDSLPackage#getBDSLBrsDefinition_Predicates()
   * @model containment="true"
   * @generated
   */
  EList<PredicateVarReference> getPredicates();

} // BDSLBrsDefinition
