/**
 * generated by Xtext 2.32.0
 */
package org.bigraphs.dsl.bDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>React Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.bigraphs.dsl.bDSL.BDSLReactDefinition#getRedex <em>Redex</em>}</li>
 *   <li>{@link org.bigraphs.dsl.bDSL.BDSLReactDefinition#getReactum <em>Reactum</em>}</li>
 * </ul>
 *
 * @see org.bigraphs.dsl.bDSL.BDSLPackage#getBDSLReactDefinition()
 * @model
 * @generated
 */
public interface BDSLReactDefinition extends EObject
{
  /**
   * Returns the value of the '<em><b>Redex</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Redex</em>' containment reference.
   * @see #setRedex(EObject)
   * @see org.bigraphs.dsl.bDSL.BDSLPackage#getBDSLReactDefinition_Redex()
   * @model containment="true"
   * @generated
   */
  EObject getRedex();

  /**
   * Sets the value of the '{@link org.bigraphs.dsl.bDSL.BDSLReactDefinition#getRedex <em>Redex</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Redex</em>' containment reference.
   * @see #getRedex()
   * @generated
   */
  void setRedex(EObject value);

  /**
   * Returns the value of the '<em><b>Reactum</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reactum</em>' containment reference.
   * @see #setReactum(EObject)
   * @see org.bigraphs.dsl.bDSL.BDSLPackage#getBDSLReactDefinition_Reactum()
   * @model containment="true"
   * @generated
   */
  EObject getReactum();

  /**
   * Sets the value of the '{@link org.bigraphs.dsl.bDSL.BDSLReactDefinition#getReactum <em>Reactum</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Reactum</em>' containment reference.
   * @see #getReactum()
   * @generated
   */
  void setReactum(EObject value);

} // BDSLReactDefinition
