/**
 * generated by Xtext 2.32.0
 */
package org.bigraphs.dsl.bDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>BRS Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.bigraphs.dsl.bDSL.BDSLPackage#getBRSDefinition()
 * @model
 * @generated
 */
public interface BRSDefinition extends AbstractNamedSignatureElement, BigraphBdslVarDeclOrReference
{
} // BRSDefinition
