/**
 * generated by Xtext 2.32.0
 */
package org.bigraphs.dsl.bDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>BRS Started Callback</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.bigraphs.dsl.bDSL.BDSLPackage#getBRSStartedCallback()
 * @model
 * @generated
 */
public interface BRSStartedCallback extends BdslCallbackMethods
{
} // BRSStartedCallback
