/**
 * generated by Xtext 2.32.0
 */
package org.bigraphs.dsl.bDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Create Random Bigraph Method</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.bigraphs.dsl.bDSL.CreateRandomBigraphMethod#getN <em>N</em>}</li>
 *   <li>{@link org.bigraphs.dsl.bDSL.CreateRandomBigraphMethod#getT <em>T</em>}</li>
 *   <li>{@link org.bigraphs.dsl.bDSL.CreateRandomBigraphMethod#getP <em>P</em>}</li>
 * </ul>
 *
 * @see org.bigraphs.dsl.bDSL.BDSLPackage#getCreateRandomBigraphMethod()
 * @model
 * @generated
 */
public interface CreateRandomBigraphMethod extends AssignableBigraphExpressionWithExplicitSig
{
  /**
   * Returns the value of the '<em><b>N</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>N</em>' attribute.
   * @see #setN(int)
   * @see org.bigraphs.dsl.bDSL.BDSLPackage#getCreateRandomBigraphMethod_N()
   * @model
   * @generated
   */
  int getN();

  /**
   * Sets the value of the '{@link org.bigraphs.dsl.bDSL.CreateRandomBigraphMethod#getN <em>N</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>N</em>' attribute.
   * @see #getN()
   * @generated
   */
  void setN(int value);

  /**
   * Returns the value of the '<em><b>T</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>T</em>' attribute.
   * @see #setT(int)
   * @see org.bigraphs.dsl.bDSL.BDSLPackage#getCreateRandomBigraphMethod_T()
   * @model
   * @generated
   */
  int getT();

  /**
   * Sets the value of the '{@link org.bigraphs.dsl.bDSL.CreateRandomBigraphMethod#getT <em>T</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>T</em>' attribute.
   * @see #getT()
   * @generated
   */
  void setT(int value);

  /**
   * Returns the value of the '<em><b>P</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>P</em>' attribute.
   * @see #setP(float)
   * @see org.bigraphs.dsl.bDSL.BDSLPackage#getCreateRandomBigraphMethod_P()
   * @model
   * @generated
   */
  float getP();

  /**
   * Sets the value of the '{@link org.bigraphs.dsl.bDSL.CreateRandomBigraphMethod#getP <em>P</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>P</em>' attribute.
   * @see #getP()
   * @generated
   */
  void setP(float value);

} // CreateRandomBigraphMethod
