/**
 * generated by Xtext 2.32.0
 */
package org.bigraphs.dsl.bDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Elementary Bigraphs</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.bigraphs.dsl.bDSL.BDSLPackage#getElementaryBigraphs()
 * @model
 * @generated
 */
public interface ElementaryBigraphs extends AbstractBigraphDeclaration
{
} // ElementaryBigraphs
