/**
 * generated by Xtext 2.32.0
 */
package org.bigraphs.dsl.bDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Export Method</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.bigraphs.dsl.bDSL.ExportMethod#getVariable <em>Variable</em>}</li>
 *   <li>{@link org.bigraphs.dsl.bDSL.ExportMethod#getFormat <em>Format</em>}</li>
 *   <li>{@link org.bigraphs.dsl.bDSL.ExportMethod#getResourcePath <em>Resource Path</em>}</li>
 * </ul>
 *
 * @see org.bigraphs.dsl.bDSL.BDSLPackage#getExportMethod()
 * @model
 * @generated
 */
public interface ExportMethod extends MethodStatements
{
  /**
   * Returns the value of the '<em><b>Variable</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable</em>' containment reference.
   * @see #setVariable(ReferenceClassSymbol)
   * @see org.bigraphs.dsl.bDSL.BDSLPackage#getExportMethod_Variable()
   * @model containment="true"
   * @generated
   */
  ReferenceClassSymbol getVariable();

  /**
   * Sets the value of the '{@link org.bigraphs.dsl.bDSL.ExportMethod#getVariable <em>Variable</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variable</em>' containment reference.
   * @see #getVariable()
   * @generated
   */
  void setVariable(ReferenceClassSymbol value);

  /**
   * Returns the value of the '<em><b>Format</b></em>' attribute.
   * The literals are from the enumeration {@link org.bigraphs.dsl.bDSL.ExportFormat}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Format</em>' attribute.
   * @see org.bigraphs.dsl.bDSL.ExportFormat
   * @see #setFormat(ExportFormat)
   * @see org.bigraphs.dsl.bDSL.BDSLPackage#getExportMethod_Format()
   * @model
   * @generated
   */
  ExportFormat getFormat();

  /**
   * Sets the value of the '{@link org.bigraphs.dsl.bDSL.ExportMethod#getFormat <em>Format</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Format</em>' attribute.
   * @see org.bigraphs.dsl.bDSL.ExportFormat
   * @see #getFormat()
   * @generated
   */
  void setFormat(ExportFormat value);

  /**
   * Returns the value of the '<em><b>Resource Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Resource Path</em>' attribute.
   * @see #setResourcePath(String)
   * @see org.bigraphs.dsl.bDSL.BDSLPackage#getExportMethod_ResourcePath()
   * @model
   * @generated
   */
  String getResourcePath();

  /**
   * Sets the value of the '{@link org.bigraphs.dsl.bDSL.ExportMethod#getResourcePath <em>Resource Path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Resource Path</em>' attribute.
   * @see #getResourcePath()
   * @generated
   */
  void setResourcePath(String value);

} // ExportMethod
