/**
 * generated by Xtext 2.32.0
 */
package org.bigraphs.dsl.bDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Local Predicate Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.bigraphs.dsl.bDSL.LocalPredicateDeclaration#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see org.bigraphs.dsl.bDSL.BDSLPackage#getLocalPredicateDeclaration()
 * @model
 * @generated
 */
public interface LocalPredicateDeclaration extends AbstractNamedSignatureElement, BigraphPredDeclOrReference
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link org.bigraphs.dsl.bDSL.PredicateType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see org.bigraphs.dsl.bDSL.PredicateType
   * @see #setType(PredicateType)
   * @see org.bigraphs.dsl.bDSL.BDSLPackage#getLocalPredicateDeclaration_Type()
   * @model
   * @generated
   */
  PredicateType getType();

  /**
   * Sets the value of the '{@link org.bigraphs.dsl.bDSL.LocalPredicateDeclaration#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see org.bigraphs.dsl.bDSL.PredicateType
   * @see #getType()
   * @generated
   */
  void setType(PredicateType value);

} // LocalPredicateDeclaration
