/**
 * generated by Xtext 2.32.0
 */
package org.bigraphs.dsl.bDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Multi</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.bigraphs.dsl.bDSL.Multi#getLeft <em>Left</em>}</li>
 *   <li>{@link org.bigraphs.dsl.bDSL.Multi#getOperator <em>Operator</em>}</li>
 *   <li>{@link org.bigraphs.dsl.bDSL.Multi#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see org.bigraphs.dsl.bDSL.BDSLPackage#getMulti()
 * @model
 * @generated
 */
public interface Multi extends BigraphExpression
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(BigraphExpression)
   * @see org.bigraphs.dsl.bDSL.BDSLPackage#getMulti_Left()
   * @model containment="true"
   * @generated
   */
  BigraphExpression getLeft();

  /**
   * Sets the value of the '{@link org.bigraphs.dsl.bDSL.Multi#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(BigraphExpression value);

  /**
   * Returns the value of the '<em><b>Operator</b></em>' attribute.
   * The literals are from the enumeration {@link org.bigraphs.dsl.bDSL.BinaryNestingOperator}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operator</em>' attribute.
   * @see org.bigraphs.dsl.bDSL.BinaryNestingOperator
   * @see #setOperator(BinaryNestingOperator)
   * @see org.bigraphs.dsl.bDSL.BDSLPackage#getMulti_Operator()
   * @model
   * @generated
   */
  BinaryNestingOperator getOperator();

  /**
   * Sets the value of the '{@link org.bigraphs.dsl.bDSL.Multi#getOperator <em>Operator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operator</em>' attribute.
   * @see org.bigraphs.dsl.bDSL.BinaryNestingOperator
   * @see #getOperator()
   * @generated
   */
  void setOperator(BinaryNestingOperator value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(BigraphExpression)
   * @see org.bigraphs.dsl.bDSL.BDSLPackage#getMulti_Right()
   * @model containment="true"
   * @generated
   */
  BigraphExpression getRight();

  /**
   * Sets the value of the '{@link org.bigraphs.dsl.bDSL.Multi#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(BigraphExpression value);

} // Multi
