/**
 * generated by Xtext 2.32.0
 */
package org.bigraphs.dsl.bDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Reference Class Symbol</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.bigraphs.dsl.bDSL.ReferenceClassSymbol#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see org.bigraphs.dsl.bDSL.BDSLPackage#getReferenceClassSymbol()
 * @model
 * @generated
 */
public interface ReferenceClassSymbol extends AssignableBigraphExpression
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' reference.
   * @see #setType(AbstractNamedSignatureElement)
   * @see org.bigraphs.dsl.bDSL.BDSLPackage#getReferenceClassSymbol_Type()
   * @model
   * @generated
   */
  AbstractNamedSignatureElement getType();

  /**
   * Sets the value of the '{@link org.bigraphs.dsl.bDSL.ReferenceClassSymbol#getType <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' reference.
   * @see #getType()
   * @generated
   */
  void setType(AbstractNamedSignatureElement value);

} // ReferenceClassSymbol
