/**
 * generated by Xtext 2.32.0
 */
package org.bigraphs.dsl.bDSL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>UDF Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.bigraphs.dsl.bDSL.UDFOperation#getExpression <em>Expression</em>}</li>
 * </ul>
 *
 * @see org.bigraphs.dsl.bDSL.BDSLPackage#getUDFOperation()
 * @model
 * @generated
 */
public interface UDFOperation extends AbstractMainStatements, CallbackStatements
{
  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference list.
   * The list contents are of type {@link org.bigraphs.dsl.bDSL.XExpression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference list.
   * @see org.bigraphs.dsl.bDSL.BDSLPackage#getUDFOperation_Expression()
   * @model containment="true"
   * @generated
   */
  EList<XExpression> getExpression();

} // UDFOperation
