/**
 * generated by Xtext 2.32.0
 */
package org.bigraphs.dsl.bDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>XExpression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.bigraphs.dsl.bDSL.BDSLPackage#getXExpression()
 * @model
 * @generated
 */
public interface XExpression extends EObject
{
} // XExpression
